#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import os
import sys
import subprocess

# Python 2/3 compatibility.
if sys.version_info >= (3,0):
	inp = input
else:
  inp = raw_input

def prompt(msg, string, default = ''):
  if msg != "":
    print(msg)
  if default != "":
    x = inp("\x1b[35m> %s [%s]: \x1b[39;49;00m" % (string, default))
  else:
    x = inp("\x1b[35m> %s: \x1b[39;49;00m" % (string))
  print("")
  return x

if __name__ == '__main__':
  
  # Shortcut for setup on Hyak
  if len(sys.argv) == 2:
    if sys.argv[1] == 'hyak':
      datadir = '/gscratch/vsm/rodluger/lightcurves'
      ttvpath = '/usr/lusers/rodluger/src/templar/ttvs'
      
  else:
  
    print("\x1b[01m%s\x1b[39;49;00m" % "Welcome to the Eyepiece setup utility.")
    print("")
  
    # Install kplr?
    print("First, let's check if you have \x1b[01mkplr\x1b[39;49;00m installed.")
    print("")
    try:
      import kplr
    except ImportError:
      print("Uh-oh, doesn't look like you have it. I'm going to try to install\nit for you using \x1b[01mpip install\x1b[39;49;00m. If you'd rather do it manually,\nhit \x1b[01mCtrl+C\x1b[39;49;00m to get out of here, and run this utility again later.\n")
      prompt("", "Press Enter to continue", "")
      try:
        subprocess.call(["pip", "install", "kplr"])
      except:
        print("Error installing \x1b[01mkplr\x1b[39;49;00m. Please do it manually and run this utility again.\n")
        sys.exit(1)
      print("")  
    
    # Options
    print("Please enter values for the following settings (just press Enter to")
    print("accept a default value, if one is given in brackets).")
    print("")
  
    # Get lightcurve directory
    datadir = os.path.abspath(prompt("Where should the lightcurves be stored?", 
                                     "Path to lightcurves", "."))
    if not os.path.exists(datadir):
      os.makedirs(datadir)
  
    # Get TTV path
    ttvpath = os.path.abspath(prompt("If you have a folder containing the transit times of all KOIs,\nplease provide its path here.", 
                                     "Path to transit times", ""))
  
  # Save the options
  defaults = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'eyepiece', 'defaults.py')  
  with open(defaults, 'r') as f:
    foo = f.read()
  with open(defaults, 'w') as f:
    print(foo.replace("'/Users/rodrigo/src/eyepiece/lightcurves'", "'%s'" % datadir).replace("'/Users/rodrigo/src/templar/ttvs'", "'%s'" % ttvpath), file = f)

  print("All done! These options were stored in the file \x1b[01mdefaults.py\x1b[39;49;00m.")
  print("")