#!/bin/sh
#PBS -o /usr/lusers/rodluger/tmp/tmp_o.txt
#PBS -e /usr/lusers/rodluger/tmp/tmp_e.txt
#PBS -M rodluger@uw.edu
#PBS -m abe
#
#
# Please provide an input file when running this script:
#
# >>> qsub -vINPUTFILE=input.py -l nodes=5:ppn=12,feature=12core,mem=40gb,walltime=2:00:00 mpi.pbs
#
#

# Run the job.
cd /usr/lusers/rodluger/src/eyepiece/scripts
mpiexec -np $PBS_NP python mpi.py $INPUTFILE &>> mpi.log

# Plot results.
python plot.py $INPUTFILE &>> mpi.log